### ISSUE TITLE
Please safe me from this EAR RAPE!  🚨 

### ISSUE THREAD

**Issue by EasyCompZLD** [inferno-collection/Fire-Alarm#15]
**Describe the bug**
I cannot control the  panel at all soon as it is openend, it waits for my imputes but never feel it as if there is a transparent layer with a Z value of to high but none off our scripts do that. I can only F8 > quit it..
**Steps to reproduce**
next time I test the panel first before smash a button ;-)

**Comment by cm8263** [comment]
https://github.com/inferno-collection/Fire-Alarm/wiki/How%20to%20use%20the%20control%20panel

**Comment by EasyCompZLD** [comment]
My friend I used to be a voluntary, fighter against the fires 🔥. 

Nowadays I have to much work to do and we’ll it might just happen to be that we ourselves developed both hard and software for similar machines, but please read my orginal post again.  

I told you, that the menu doesn’t not respond to any Input, I can press every button or try esc or backspace to exit the menu but nope the only way to exit is by re-logging

**Comment by cm8263** [comment]
> My friend I used to be a voluntary, fighter against the fires 🔥.
> 
> Nowadays I have to much work to do and we’ll it might just happen to be that we ourselves developed both hard and software for similar machines, but please read my orginal post again.
> 
> I told you, that the menu doesn’t not respond to any Input, I can press every button or try esc or backspace to exit the menu but nope the only way to exit is by re-logging

That is not what you said at all, and has nothing to do with your issue title.

> I cannot control the panel at all soon as it is opened

Regardless, the code has not been touched in 17 months and worked at the time of publishing. If you are on the Beta branch, and vice versa. This is an old resource and until it is updated I cannot provide any support.
