### ISSUE TITLE
[Bug] Can't press 'E' to open the panel 

### ISSUE THREAD

**Issue by Firstmada** [inferno-collection/Fire-Alarm#6]
**Describe the bug**
Can't press 'E' to open the panel, though the panel object spawns in and I can pull alarms

**Steps to reproduce**
Install the script and try to open panel

**Expected behavior**
The panel should open and let me use it

**Screenshots**
N/A

**Resource version**
Latest Release

**Additional context**
N/A

**Comment by cm8263** [comment]
Can you download a fresh copy, and run it on an empty server (I.e. it is the only resource running), and let me know what happens please.

**Comment by Firstmada** [comment]
Tried that, figured it was a map mod spawning an elec box prop in the same place as the one in this script. Now on the clean server, I have no elec box prop for the panel at all spawning in and still can't press E. No console errors being displayed.

**Comment by Firstmada** [comment]
Worked, thanks.

**Comment by cm8263** [comment]
Likely a conflicting resource then, let me know when you find which one it is and I'll look into it.

**Comment by cm8263** [comment]
Had no other reports of this issue, likey a conflicting resource.
